spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3309/microservices
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  devtools:
    add-properties: false
  main:
    banner-mode: off

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework: WARN
      hibernate: WARN
    com:
      zaxxer: WARN
